### ISSUE TITLE
Download fails for instagram 

### ISSUE THREAD

**Issue by bladecell** [ggogel/SocialMediaDownloadMaubot#11] opened 2024-10-08 06:37 UTC
Hey, getting error using this plugin

```
[2024-10-08 06:30:39,850] [DEBUG@urllib3.connectionpool] Starting new HTTPS connection (1): www.instagram.com:443
[2024-10-08 06:30:40,071] [DEBUG@urllib3.connectionpool] https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAtEltPgZb_%22%7D HTTP/11" 401 119
JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
[2024-10-08 06:30:41,067] [DEBUG@urllib3.connectionpool] [https://www.instagram.com:443](https://www.instagram.com/) "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAtEltPgZb_%22%7D HTTP/11" 401 119
JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
[2024-10-08 06:30:46,344] [DEBUG@urllib3.connectionpool] https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAtEltPgZb_%22%7D HTTP/11" 401 119
[2024-10-08 06:30:46,353] [ERROR@maubot.client.@bumnotifications:matrix.org] Failed to run handler
Traceback (most recent call last):
  File "/data/plugins/me.gogel.maubot.socialmediadownload-v1.4.2.mbp/instaloader/instaloadercontext.py", line 413, in get_json
    raise ConnectionException("HTTP error code {}.".format(resp.status_code))
instaloader.exceptions.ConnectionException: HTTP error code 401.
all values are hidden
During handling of the above exception, another exception occurred:
all values are hidden
Traceback (most recent call last):
  File "/data/plugins/me.gogel.maubot.socialmediadownload-v1.4.2.mbp/instaloader/instaloadercontext.py", line 413, in get_json
    raise ConnectionException("HTTP error code {}.".format(resp.status_code))
instaloader.exceptions.ConnectionException: HTTP error code 401.
all values are hidden
During handling of the above exception, another exception occurred:
all values are hidden
Traceback (most recent call last):
  File "/data/plugins/me.gogel.maubot.socialmediadownload-v1.4.2.mbp/instaloader/instaloadercontext.py", line 413, in get_json
    raise ConnectionException("HTTP error code {}.".format(resp.status_code))
instaloader.exceptions.ConnectionException: HTTP error code 401.
all values are hidden
The above exception was the direct cause of the following exception:
all values are hidden
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/mautrix/client/syncer.py", line 236, in _catch_errors
    await handler(data)
  File "/data/plugins/me.gogel.maubot.socialmediadownload-v1.4.2.mbp/socialmediadownload.py", line 58, in on_message
    await self.handle_instagram(evt, url_tup)
  File "/data/plugins/me.gogel.maubot.socialmediadownload-v1.4.2.mbp/socialmediadownload.py", line 188, in handle_instagram
    post = instaloader.Post.from_shortcode(L.context, shortcode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/plugins/me.gogel.maubot.socialmediadownload-v1.4.2.mbp/instaloader/structures.py", line 207, in from_shortcode
    post._node = post._full_metadata
                 ^^^^^^^^^^^^^^^^^^^
  File "/data/plugins/me.gogel.maubot.socialmediadownload-v1.4.2.mbp/instaloader/structures.py", line 324, in _full_metadata
    self._obtain_metadata()
  File "/data/plugins/me.gogel.maubot.socialmediadownload-v1.4.2.mbp/instaloader/structures.py", line 311, in _obtain_metadata
    pic_json = self._context.graphql_query(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/plugins/me.gogel.maubot.socialmediadownload-v1.4.2.mbp/instaloader/instaloadercontext.py", line 474, in graphql_query
    resp_json = self.get_json('graphql/query',
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/plugins/me.gogel.maubot.socialmediadownload-v1.4.2.mbp/instaloader/instaloadercontext.py", line 439, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/plugins/me.gogel.maubot.socialmediadownload-v1.4.2.mbp/instaloader/instaloadercontext.py", line 439, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/plugins/me.gogel.maubot.socialmediadownload-v1.4.2.mbp/instaloader/instaloadercontext.py", line 429, in get_json
    raise ConnectionException(error_string) from err
instaloader.exceptions.ConnectionException: JSON Query to graphql/query: HTTP error code 401.

```

Is this related to the instagram anonymous access?

**Comment by ggogel** [comment] 2024-10-21 08:56
Duplicate of #10

**Closed as completed by ggogel** 2024-10-21 08:56 UTC
